name: build 2
on:
  workflow_run:
    workflows:
      - "build"
    types:
      - completed
      - requested
      - in_progress

jobs:
  build2:
    runs-on: arc-runner-set
    steps:
      - run: echo "${{ github.event.workflow_run.conclusion }}"
