name: workflow-run-event
on:
  workflow_run:
    workflows:
      - "build"
    types:
      - completed
      - requested
      - in_progress

jobs:
  build2:
    runs-on: arc-runner-set
    steps:
      - run: echo "${{ toJSON(github.event) }}"
